// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AddModelData, AddModelErrors, AddModelResponses, AddSampleData, AddSampleErrors, AddSampleResponses, ApproveData, ApproveErrors, ApproveResponses, AuditTrailData, AuditTrailErrors, AuditTrailResponses, CreateSheetData, CreateSheetErrors, CreateSheetResponses, CreateSpecData, CreateSpecErrors, CreateSpecResponses, ExportXlsxData, ExportXlsxErrors, ExportXlsxResponses, GetFileData, GetFileErrors, GetFileResponses, GetSheetData, GetSheetErrors, GetSheetResponses, GetSpecData, GetSpecErrors, GetSpecResponses, HealthData, HealthResponses, JudgeSheetData, JudgeSheetErrors, JudgeSheetResponses, ListSheetsData, ListSheetsErrors, ListSheetsResponses, ListSpecsData, ListSpecsErrors, ListSpecsResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, MeData, MeErrors, MeResponses, RejectData, RejectErrors, RejectResponses, TransitionSheetData, TransitionSheetErrors, TransitionSheetResponses, UpdateItemValuesData, UpdateItemValuesErrors, UpdateItemValuesResponses, UpdateSampleData, UpdateSampleErrors, UpdateSampleResponses, UploadPdfData, UploadPdfErrors, UploadPdfResponses, UploadPhotoData, UploadPhotoErrors, UploadPhotoResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/api/auth/logout', ...options });

/**
 * Me
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, MeErrors, ThrowOnError> => (options?.client ?? client).get<MeResponses, MeErrors, ThrowOnError>({ url: '/api/auth/me', ...options });

/**
 * List Specs
 */
export const listSpecs = <ThrowOnError extends boolean = false>(options?: Options<ListSpecsData, ThrowOnError>): RequestResult<ListSpecsResponses, ListSpecsErrors, ThrowOnError> => (options?.client ?? client).get<ListSpecsResponses, ListSpecsErrors, ThrowOnError>({ url: '/api/specs', ...options });

/**
 * Create Spec
 *
 * 建立標準:同名自動遞增版本(標準版本化 — 舊單仍指向舊版,判定可重現)。
 */
export const createSpec = <ThrowOnError extends boolean = false>(options: Options<CreateSpecData, ThrowOnError>): RequestResult<CreateSpecResponses, CreateSpecErrors, ThrowOnError> => (options.client ?? client).post<CreateSpecResponses, CreateSpecErrors, ThrowOnError>({
    url: '/api/specs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Spec
 */
export const getSpec = <ThrowOnError extends boolean = false>(options: Options<GetSpecData, ThrowOnError>): RequestResult<GetSpecResponses, GetSpecErrors, ThrowOnError> => (options.client ?? client).get<GetSpecResponses, GetSpecErrors, ThrowOnError>({ url: '/api/specs/{spec_id}', ...options });

/**
 * List Sheets
 */
export const listSheets = <ThrowOnError extends boolean = false>(options?: Options<ListSheetsData, ThrowOnError>): RequestResult<ListSheetsResponses, ListSheetsErrors, ThrowOnError> => (options?.client ?? client).get<ListSheetsResponses, ListSheetsErrors, ThrowOnError>({ url: '/api/sheets', ...options });

/**
 * Create Sheet
 */
export const createSheet = <ThrowOnError extends boolean = false>(options: Options<CreateSheetData, ThrowOnError>): RequestResult<CreateSheetResponses, CreateSheetErrors, ThrowOnError> => (options.client ?? client).post<CreateSheetResponses, CreateSheetErrors, ThrowOnError>({
    url: '/api/sheets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Sheet
 */
export const getSheet = <ThrowOnError extends boolean = false>(options: Options<GetSheetData, ThrowOnError>): RequestResult<GetSheetResponses, GetSheetErrors, ThrowOnError> => (options.client ?? client).get<GetSheetResponses, GetSheetErrors, ThrowOnError>({ url: '/api/sheets/{sheet_id}', ...options });

/**
 * Add Model
 */
export const addModel = <ThrowOnError extends boolean = false>(options: Options<AddModelData, ThrowOnError>): RequestResult<AddModelResponses, AddModelErrors, ThrowOnError> => (options.client ?? client).post<AddModelResponses, AddModelErrors, ThrowOnError>({
    url: '/api/sheets/{sheet_id}/models',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Item Values
 */
export const updateItemValues = <ThrowOnError extends boolean = false>(options: Options<UpdateItemValuesData, ThrowOnError>): RequestResult<UpdateItemValuesResponses, UpdateItemValuesErrors, ThrowOnError> => (options.client ?? client).patch<UpdateItemValuesResponses, UpdateItemValuesErrors, ThrowOnError>({
    url: '/api/models/{model_id}/values',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add Sample
 */
export const addSample = <ThrowOnError extends boolean = false>(options: Options<AddSampleData, ThrowOnError>): RequestResult<AddSampleResponses, AddSampleErrors, ThrowOnError> => (options.client ?? client).post<AddSampleResponses, AddSampleErrors, ThrowOnError>({
    url: '/api/models/{model_id}/samples',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload Pdf
 */
export const uploadPdf = <ThrowOnError extends boolean = false>(options: Options<UploadPdfData, ThrowOnError>): RequestResult<UploadPdfResponses, UploadPdfErrors, ThrowOnError> => (options.client ?? client).post<UploadPdfResponses, UploadPdfErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/samples/{sample_id}/pdf',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Update Sample
 */
export const updateSample = <ThrowOnError extends boolean = false>(options: Options<UpdateSampleData, ThrowOnError>): RequestResult<UpdateSampleResponses, UpdateSampleErrors, ThrowOnError> => (options.client ?? client).patch<UpdateSampleResponses, UpdateSampleErrors, ThrowOnError>({
    url: '/api/samples/{sample_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Judge Sheet
 *
 * 執行綜合判定:逐型號跑判定引擎並推進狀態到 judged。
 */
export const judgeSheet = <ThrowOnError extends boolean = false>(options: Options<JudgeSheetData, ThrowOnError>): RequestResult<JudgeSheetResponses, JudgeSheetErrors, ThrowOnError> => (options.client ?? client).post<JudgeSheetResponses, JudgeSheetErrors, ThrowOnError>({ url: '/api/sheets/{sheet_id}/judge', ...options });

/**
 * Transition Sheet
 *
 * 一般狀態轉移(送審、啟動二次拆檢、歸檔)。簽核/退件走 review API。
 */
export const transitionSheet = <ThrowOnError extends boolean = false>(options: Options<TransitionSheetData, ThrowOnError>): RequestResult<TransitionSheetResponses, TransitionSheetErrors, ThrowOnError> => (options.client ?? client).post<TransitionSheetResponses, TransitionSheetErrors, ThrowOnError>({
    url: '/api/sheets/{sheet_id}/transition',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload Photo
 */
export const uploadPhoto = <ThrowOnError extends boolean = false>(options: Options<UploadPhotoData, ThrowOnError>): RequestResult<UploadPhotoResponses, UploadPhotoErrors, ThrowOnError> => (options.client ?? client).post<UploadPhotoResponses, UploadPhotoErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/samples/{sample_id}/photos',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get File
 */
export const getFile = <ThrowOnError extends boolean = false>(options: Options<GetFileData, ThrowOnError>): RequestResult<GetFileResponses, GetFileErrors, ThrowOnError> => (options.client ?? client).get<GetFileResponses, GetFileErrors, ThrowOnError>({ url: '/api/files/{filename}', ...options });

/**
 * Approve
 */
export const approve = <ThrowOnError extends boolean = false>(options: Options<ApproveData, ThrowOnError>): RequestResult<ApproveResponses, ApproveErrors, ThrowOnError> => (options.client ?? client).post<ApproveResponses, ApproveErrors, ThrowOnError>({
    url: '/api/review/sheets/{sheet_id}/approve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reject
 */
export const reject = <ThrowOnError extends boolean = false>(options: Options<RejectData, ThrowOnError>): RequestResult<RejectResponses, RejectErrors, ThrowOnError> => (options.client ?? client).post<RejectResponses, RejectErrors, ThrowOnError>({
    url: '/api/review/sheets/{sheet_id}/reject',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Audit Trail
 */
export const auditTrail = <ThrowOnError extends boolean = false>(options: Options<AuditTrailData, ThrowOnError>): RequestResult<AuditTrailResponses, AuditTrailErrors, ThrowOnError> => (options.client ?? client).get<AuditTrailResponses, AuditTrailErrors, ThrowOnError>({ url: '/api/review/sheets/{sheet_id}/audit', ...options });

/**
 * Export Xlsx
 *
 * 匯出檢驗報表 Excel。
 *
 * 注意:目前為系統預設版面;待取得公司現行報表模板檔後改為模板填值,
 * 使格式與紙本 100% 一致(docs/requirements.md §7)。
 */
export const exportXlsx = <ThrowOnError extends boolean = false>(options: Options<ExportXlsxData, ThrowOnError>): RequestResult<ExportXlsxResponses, ExportXlsxErrors, ThrowOnError> => (options.client ?? client).get<ExportXlsxResponses, ExportXlsxErrors, ThrowOnError>({ url: '/api/export/sheets/{sheet_id}/xlsx', ...options });

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });
