// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_upload_pdf
 */
export type BodyUploadPdf = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_photo
 */
export type BodyUploadPhoto = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemValuesUpdate
 */
export type ItemValuesUpdate = {
    /**
     * Item Values
     */
    item_values: {
        [key: string]: unknown;
    };
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ModelCreate
 */
export type ModelCreate = {
    /**
     * Spec Template Id
     */
    spec_template_id: number;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Batch Code
     */
    batch_code?: string;
};

/**
 * ModelOut
 */
export type ModelOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Spec Template Id
     */
    spec_template_id: number;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Batch Code
     */
    batch_code: string;
    /**
     * Item Values
     */
    item_values: {
        [key: string]: unknown;
    };
    /**
     * Result
     */
    result: string;
    /**
     * Judgement
     */
    judgement: {
        [key: string]: unknown;
    };
    /**
     * Samples
     */
    samples?: Array<SampleOut>;
};

/**
 * ParseResult
 */
export type ParseResult = {
    /**
     * Values
     */
    values: {
        [key: string]: number;
    };
    /**
     * Missing
     */
    missing: Array<string>;
    /**
     * Has Text Layer
     */
    has_text_layer: boolean;
};

/**
 * PhotoOut
 */
export type PhotoOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Kind
     */
    kind: string;
    /**
     * Filename
     */
    filename: string;
};

/**
 * ReviewRequest
 */
export type ReviewRequest = {
    /**
     * Comment
     */
    comment?: string;
};

/**
 * SampleCreate
 */
export type SampleCreate = {
    /**
     * Seq
     */
    seq?: number;
};

/**
 * SampleOut
 */
export type SampleOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Seq
     */
    seq: number;
    /**
     * Photometric
     */
    photometric: {
        [key: string]: unknown;
    };
    /**
     * Source
     */
    source: string;
    /**
     * Pdf Filename
     */
    pdf_filename: string;
    /**
     * Confirmed
     */
    confirmed: boolean;
    /**
     * Photos
     */
    photos?: Array<PhotoOut>;
};

/**
 * SampleUpdate
 */
export type SampleUpdate = {
    /**
     * Photometric
     */
    photometric?: {
        [key: string]: unknown;
    } | null;
    /**
     * Confirmed
     */
    confirmed?: boolean | null;
};

/**
 * SheetCreate
 */
export type SheetCreate = {
    /**
     * Container No
     */
    container_no: string;
    /**
     * Seal No
     */
    seal_no?: string;
    /**
     * Unstuffing Date
     */
    unstuffing_date?: string;
    /**
     * Qc Date
     */
    qc_date?: string;
};

/**
 * SheetListItem
 */
export type SheetListItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Container No
     */
    container_no: string;
    /**
     * Qc Date
     */
    qc_date: string;
    /**
     * Status
     */
    status: string;
};

/**
 * SheetOut
 */
export type SheetOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Container No
     */
    container_no: string;
    /**
     * Seal No
     */
    seal_no: string;
    /**
     * Unstuffing Date
     */
    unstuffing_date: string;
    /**
     * Qc Date
     */
    qc_date: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created By
     */
    created_by: number;
    /**
     * Model Inspections
     */
    model_inspections?: Array<ModelOut>;
};

/**
 * SpecCreate
 */
export type SpecCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Product Category
     */
    product_category: string;
    /**
     * Items
     */
    items: Array<SpecItemIn>;
};

/**
 * SpecItemIn
 */
export type SpecItemIn = {
    /**
     * Key
     */
    key: string;
    /**
     * Label
     */
    label: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Rule
     */
    rule?: {
        [key: string]: unknown;
    };
    /**
     * Standard Text
     */
    standard_text?: string;
};

/**
 * SpecOut
 */
export type SpecOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Product Category
     */
    product_category: string;
    /**
     * Version
     */
    version: number;
    /**
     * Items
     */
    items: Array<unknown>;
};

/**
 * TransitionRequest
 */
export type TransitionRequest = {
    /**
     * To Status
     */
    to_status: string;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Role
     */
    role: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * Response Logout
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListSpecsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/specs';
};

export type ListSpecsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSpecsError = ListSpecsErrors[keyof ListSpecsErrors];

export type ListSpecsResponses = {
    /**
     * Response List Specs
     *
     * Successful Response
     */
    200: Array<SpecOut>;
};

export type ListSpecsResponse = ListSpecsResponses[keyof ListSpecsResponses];

export type CreateSpecData = {
    body: SpecCreate;
    path?: never;
    query?: never;
    url: '/api/specs';
};

export type CreateSpecErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSpecError = CreateSpecErrors[keyof CreateSpecErrors];

export type CreateSpecResponses = {
    /**
     * Successful Response
     */
    200: SpecOut;
};

export type CreateSpecResponse = CreateSpecResponses[keyof CreateSpecResponses];

export type GetSpecData = {
    body?: never;
    path: {
        /**
         * Spec Id
         */
        spec_id: number;
    };
    query?: never;
    url: '/api/specs/{spec_id}';
};

export type GetSpecErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSpecError = GetSpecErrors[keyof GetSpecErrors];

export type GetSpecResponses = {
    /**
     * Successful Response
     */
    200: SpecOut;
};

export type GetSpecResponse = GetSpecResponses[keyof GetSpecResponses];

export type ListSheetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sheets';
};

export type ListSheetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSheetsError = ListSheetsErrors[keyof ListSheetsErrors];

export type ListSheetsResponses = {
    /**
     * Response List Sheets
     *
     * Successful Response
     */
    200: Array<SheetListItem>;
};

export type ListSheetsResponse = ListSheetsResponses[keyof ListSheetsResponses];

export type CreateSheetData = {
    body: SheetCreate;
    path?: never;
    query?: never;
    url: '/api/sheets';
};

export type CreateSheetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSheetError = CreateSheetErrors[keyof CreateSheetErrors];

export type CreateSheetResponses = {
    /**
     * Successful Response
     */
    200: SheetOut;
};

export type CreateSheetResponse = CreateSheetResponses[keyof CreateSheetResponses];

export type GetSheetData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: number;
    };
    query?: never;
    url: '/api/sheets/{sheet_id}';
};

export type GetSheetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSheetError = GetSheetErrors[keyof GetSheetErrors];

export type GetSheetResponses = {
    /**
     * Successful Response
     */
    200: SheetOut;
};

export type GetSheetResponse = GetSheetResponses[keyof GetSheetResponses];

export type AddModelData = {
    body: ModelCreate;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: number;
    };
    query?: never;
    url: '/api/sheets/{sheet_id}/models';
};

export type AddModelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddModelError = AddModelErrors[keyof AddModelErrors];

export type AddModelResponses = {
    /**
     * Successful Response
     */
    200: ModelOut;
};

export type AddModelResponse = AddModelResponses[keyof AddModelResponses];

export type UpdateItemValuesData = {
    body: ItemValuesUpdate;
    path: {
        /**
         * Model Id
         */
        model_id: number;
    };
    query?: never;
    url: '/api/models/{model_id}/values';
};

export type UpdateItemValuesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemValuesError = UpdateItemValuesErrors[keyof UpdateItemValuesErrors];

export type UpdateItemValuesResponses = {
    /**
     * Successful Response
     */
    200: ModelOut;
};

export type UpdateItemValuesResponse = UpdateItemValuesResponses[keyof UpdateItemValuesResponses];

export type AddSampleData = {
    body: SampleCreate;
    path: {
        /**
         * Model Id
         */
        model_id: number;
    };
    query?: never;
    url: '/api/models/{model_id}/samples';
};

export type AddSampleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddSampleError = AddSampleErrors[keyof AddSampleErrors];

export type AddSampleResponses = {
    /**
     * Successful Response
     */
    200: SampleOut;
};

export type AddSampleResponse = AddSampleResponses[keyof AddSampleResponses];

export type UploadPdfData = {
    body: BodyUploadPdf;
    path: {
        /**
         * Sample Id
         */
        sample_id: number;
    };
    query?: never;
    url: '/api/samples/{sample_id}/pdf';
};

export type UploadPdfErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadPdfError = UploadPdfErrors[keyof UploadPdfErrors];

export type UploadPdfResponses = {
    /**
     * Successful Response
     */
    200: ParseResult;
};

export type UploadPdfResponse = UploadPdfResponses[keyof UploadPdfResponses];

export type UpdateSampleData = {
    body: SampleUpdate;
    path: {
        /**
         * Sample Id
         */
        sample_id: number;
    };
    query?: never;
    url: '/api/samples/{sample_id}';
};

export type UpdateSampleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSampleError = UpdateSampleErrors[keyof UpdateSampleErrors];

export type UpdateSampleResponses = {
    /**
     * Successful Response
     */
    200: SampleOut;
};

export type UpdateSampleResponse = UpdateSampleResponses[keyof UpdateSampleResponses];

export type JudgeSheetData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: number;
    };
    query?: never;
    url: '/api/sheets/{sheet_id}/judge';
};

export type JudgeSheetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JudgeSheetError = JudgeSheetErrors[keyof JudgeSheetErrors];

export type JudgeSheetResponses = {
    /**
     * Successful Response
     */
    200: SheetOut;
};

export type JudgeSheetResponse = JudgeSheetResponses[keyof JudgeSheetResponses];

export type TransitionSheetData = {
    body: TransitionRequest;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: number;
    };
    query?: never;
    url: '/api/sheets/{sheet_id}/transition';
};

export type TransitionSheetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransitionSheetError = TransitionSheetErrors[keyof TransitionSheetErrors];

export type TransitionSheetResponses = {
    /**
     * Successful Response
     */
    200: SheetOut;
};

export type TransitionSheetResponse = TransitionSheetResponses[keyof TransitionSheetResponses];

export type UploadPhotoData = {
    body: BodyUploadPhoto;
    path: {
        /**
         * Sample Id
         */
        sample_id: number;
    };
    query?: {
        /**
         * Kind
         */
        kind?: string;
    };
    url: '/api/samples/{sample_id}/photos';
};

export type UploadPhotoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadPhotoError = UploadPhotoErrors[keyof UploadPhotoErrors];

export type UploadPhotoResponses = {
    /**
     * Successful Response
     */
    200: PhotoOut;
};

export type UploadPhotoResponse = UploadPhotoResponses[keyof UploadPhotoResponses];

export type GetFileData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/files/{filename}';
};

export type GetFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApproveData = {
    body: ReviewRequest;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: number;
    };
    query?: never;
    url: '/api/review/sheets/{sheet_id}/approve';
};

export type ApproveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveError = ApproveErrors[keyof ApproveErrors];

export type ApproveResponses = {
    /**
     * Successful Response
     */
    200: SheetOut;
};

export type ApproveResponse = ApproveResponses[keyof ApproveResponses];

export type RejectData = {
    body: ReviewRequest;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: number;
    };
    query?: never;
    url: '/api/review/sheets/{sheet_id}/reject';
};

export type RejectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RejectError = RejectErrors[keyof RejectErrors];

export type RejectResponses = {
    /**
     * Successful Response
     */
    200: SheetOut;
};

export type RejectResponse = RejectResponses[keyof RejectResponses];

export type AuditTrailData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: number;
    };
    query?: never;
    url: '/api/review/sheets/{sheet_id}/audit';
};

export type AuditTrailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditTrailError = AuditTrailErrors[keyof AuditTrailErrors];

export type AuditTrailResponses = {
    /**
     * Response Audit Trail
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type AuditTrailResponse = AuditTrailResponses[keyof AuditTrailResponses];

export type ExportXlsxData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: number;
    };
    query?: never;
    url: '/api/export/sheets/{sheet_id}/xlsx';
};

export type ExportXlsxErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportXlsxError = ExportXlsxErrors[keyof ExportXlsxErrors];

export type ExportXlsxResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Response Health
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];
